apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # grafana reaches prometheus via docker network
    isDefault: true
    editable: false
